version: '3'

services:
  db:
    image: postgres:12.2
    env_file:
      - database.env # configure postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:5.0.8
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ecommerce-gifts
    ports:
      - "3000:3000"
    env_file:
      - docker.env # configure postgres
    depends_on:
      - db
      - redis
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    env_file:
      - docker.env

volumes:
  redis:
  db: